#!/usr/bin/env node
var debug = require('debug')('sand');
var app = require('./app');
var multiplayer = require('./server/multiplayer');
var fadeRegions = require('./server/fade_regions');
var buriedItems = require('./server/buried_items');

app.set('port', process.env.PORT || 3000);

var server = app.listen(app.get('port'), function () {
	debug('Express server listening on port ' + server.address().port);
});

multiplayer.initMultiplayer(server);
fadeRegions.initialize();
buriedItems.initialize();
